// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvitgahgyioydzusrpvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2aXRnYWhneWlveWR6dXNycHZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5ODAyMjksImV4cCI6MjA3MTU1NjIyOX0.H1pO_QsPJJB1Sachgfzh6JBkz-wWsk0vQtTUvLfhNas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});