name: 📱 Cordova APK Build

on:
  workflow_dispatch:
    inputs:
      clean_build:
        description: 'Clean build'
        required: false
        default: 'true'
        type: boolean

jobs:
  build-cordova:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4
      
    - name: 📦 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: 📋 Install dependencies
      run: npm install --legacy-peer-deps
      
    - name: 🏗️ Build PWA
      run: npm run build
      
    - name: 📱 Install Cordova
      run: |
        npm install -g cordova
        cordova --version
        
    - name: ⚙️ Create Cordova project
      run: |
        # Create Cordova project
        cordova create cordova-app com.novado.app "Novado"
        cd cordova-app
        
        # Copy PWA files
        rm -rf www/*
        cp -r ../dist/* www/
        
        # Add Android platform
        cordova platform add android
        
        # Update config.xml
        cat > config.xml << 'EOF'
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.novado.app" version="1.0.0" xmlns="http://www.w3.org/ns/widgets">
    <name>Novado</name>
    <description>Безліч оголошень чекають на тебе</description>
    <author email="support@novado.com.ua" href="https://novado.com.ua">Novado Team</author>
    <content src="index.html" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <platform name="android">
        <allow-intent href="market:*" />
        <preference name="AndroidLaunchMode" value="singleTop" />
        <preference name="AndroidXEnabled" value="true" />
        <preference name="GradlePluginKotlinEnabled" value="true" />
        <preference name="GradlePluginKotlinCodeStyle" value="official" />
    </platform>
    <preference name="DisallowOverscroll" value="true" />
    <preference name="android-minSdkVersion" value="22" />
    <preference name="android-targetSdkVersion" value="34" />
</widget>
EOF
        
    - name: ☕ Setup Java for Cordova
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: 🤖 Setup Android SDK for Cordova
      uses: android-actions/setup-android@v3
      
    - name: 📱 Accept SDK licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
      
    - name: 🔧 Install Android requirements
      run: |
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0"
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-34"
        
    - name: 🏗️ Build Cordova APK
      run: |
        cd cordova-app
        
        echo "🚀 Building Cordova APK..."
        cordova build android --debug --verbose
        
        echo "📁 Checking build results:"
        find platforms/android -name "*.apk" -type f
        
        if [ -f "platforms/android/app/build/outputs/apk/debug/app-debug.apk" ]; then
          echo "✅ Cordova APK built successfully!"
          cp platforms/android/app/build/outputs/apk/debug/app-debug.apk ../novado-cordova.apk
          ls -la ../novado-cordova.apk
        else
          echo "❌ Cordova APK not found!"
          exit 1
        fi
        
    - name: 📋 Get version
      id: version
      run: echo "VERSION=$(date +'%Y.%m.%d-%H%M')-cordova" >> $GITHUB_OUTPUT
      
    - name: 🚀 Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version.outputs.VERSION }}
        name: 📱 Novado v${{ steps.version.outputs.VERSION }} (Cordova)
        body: |
          📱 **Novado APK (Cordova Build)**
          
          📅 Версія: ${{ steps.version.outputs.VERSION }}
          🏗️ Метод: Apache Cordova
          📱 Назва: **Novado**
          
          ### 📥 Встановлення:
          1. Завантажте APK нижче
          2. Увімкніть "Невідомі джерела"
          3. Встановіть APK файл
          4. Відкрийте **Novado**
          
          ### ✨ Функції:
          - 🎬 Splash screen з анімацією
          - 📱 Іконка з буквою N
          - 🇺🇦 "Безліч оголошень чекають на тебе"
          - 🔄 Автооновлення
          - 🌐 Повна функціональність
          
        files: novado-cordova.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}